export const AUTH_ACTION_TYPES = {
  USER_SIGN_UP_REQUEST: 'auth/USER_SIGN_UP_REQUEST',
  USER_SIGN_UP_SUCCESS: 'auth/USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILED: 'auth/USER_SIGN_UP_FAILED',
  USER_LOGIN_REQUEST: 'auth/USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'auth/USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'auth/USER_LOGIN_FAILED',
  USER_SIGN_OUT_REQUEST: 'user/SIGN_OUT_REQUEST',
  USER_SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
  USER_SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',
  SET_CURRENT_USER_START: 'auth/SET_CURRENT_USER_START',
  SET_CURRENT_USER_SUCCESS: 'auth/SET_CURRENT_USER_SUCCESS',
};
